#ifndef WNDPROC_H
#define WNDPROC_H

extern int wndprocFrmMainHandle;
extern int wndprocMessages[];
extern int wndprocFrmScriptOutputHandle;
extern int wndprocFrmScriptSourceHandle;
extern int wndprocMouseWheel;

#define WNDPROC_MESSAGE0_SHOW_SCRIPT_ERRORS				1
#define WNDPROC_MESSAGE0_SET_PROGRES_BAR_VALUE			2
#define WNDPROC_MESSAGE0_ENABLE_MAIN_FORM				3
#define WNDPROC_MESSAGE0_SHOW_FRAME_LIST				4
#define WNDPROC_MESSAGE0_SHOW_DEBUG_PARAM_1				5
#define WNDPROC_MESSAGE0_SHOW_DEBUG_PARAM_2				6
#define WNDPROC_MESSAGE0_SHOW_DEBUG_PARAM_3				7
#define WNDPROC_MESSAGE0_SHOW_DEBUG_PARAM_4				8
#define WNDPROC_MESSAGE0_SHOW_DEBUG_PARAM_5				9
#define WNDPROC_MESSAGE0_SHOW_OPENGL_FPS				10
#define WNDPROC_MESSAGE0_SHOW_CORE_FPS					11
#define WNDPROC_MESSAGE0_HIGHLIGHT_ERROR				12
#define WNDPROC_MESSAGE0_ACTIVATE_SCRIPT_SOURCE			13
#define WNDPROC_MESSAGE0_SHOW_ACTIVE_FRAME				14
#define WNDPROC_MESSAGE0_SHOW_MAIN_STATUS				15
#define WNDPROC_MESSAGE0_SHOW_COMPILETIME				16
#define WNDPROC_MESSAGE0_SHOW_RUNTIME					17
#define WNDPROC_MESSAGE0_SHOW_LATTICE_SIZE				18
#define WNDPROC_MESSAGE0_DEBUG_SHOW_NUMBER				19
#define WNDPROC_MESSAGE0_SHOW_USB_STATUS				20
#define WNDPROC_MESSAGE0_SHOW_ANIMATION_TITLE			21
#define WNDPROC_MESSAGE0_NO_ANIMATION_FILE_NAME			22


#endif
